authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('cadastro/', views.register, name='register'),
    path('cadastro/create/', views.register_create, name='create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('pagina_de_usuario/', views.pagina_de_usuario, name='pagina_de_usuario'),
    path('pagina_de_usuario/logout', views.logout_view, name='logout'),
    path('receitas_publicadas/', views.receitas_publicadas, name='receitas_publicadas'),
    path('receitas_em_revisao/', views.receitas_em_revisao, name='receitas_em_revisao'),
    path('receitas_em_revisao/editar_receita/<int:id>/', views.editar_receita, name='editar_receita'),
    path('cadastrar_receita/', views.cadastrar_receita, name='cadastrar_receitas'),
    path('apagar_receita/<int:id>/', views.apagar_receita, name='apagar_receita'),
]

recipesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from recipes.models import Recipe, Category
from collections import defaultdict

def add_attr(field, attr_name, attr_new_val):
    existing = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing} {attr_new_val}'.strip()

def add_placeholder(field, placeholder_val):
    add_attr(field, 'placeholder', placeholder_val)

def strong_password(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{6,}$')

    if not regex.match(password):
        raise ValidationError((
            'A Senha pracisa ter 1 letra maiuscula, 1 minuscula, 1 numero e ter pelo menos 6 caracteres'
        ),
            code='Invalid'
        )

class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        add_placeholder(self.fields['first_name'], 'Nome')
        add_placeholder(self.fields['last_name'], 'Sobrenome')
        add_placeholder(self.fields['email'], 'E-mail')
        add_placeholder(self.fields['username'], 'Usuario')
        add_placeholder(self.fields['password'], 'Senha')

    first_name = forms.CharField(
        required=True,
        error_messages={'required': 'O campo precisa conter seu nome'},
        label='Nome'
    )

    last_name = forms.CharField(
        required=True,
        error_messages={'required': 'O campo precisa conter seu sobrenome'},
        label='Sobrenome'
    )

    email = forms.EmailField(
        required=True,
        error_messages={'required': 'E-mail precisa ser valido'},
        label='E-mail',
        help_text='',
    )

    username = forms.CharField(
        required=True,
        error_messages={'required':'O campo nao pode ser vazio',
                        'min_length':'O usuario deve ter pelo menos 4 caracteres',
                        'max_length':'O usuario deve ter menos de 150 caracteres'
        },
        help_text='',
        label='Usuário',
        min_length=4,
        max_length=50,
    )

    password = forms.CharField(
        required=True,
        label='Senha',
        widget=forms.PasswordInput(attrs={
        }),
        error_messages={
            'required':'* campo obrigratorio',
        },
        validators = [strong_password]
    )

    password_confirmation = forms.CharField(
        required=True,
        label='Confirme sua Senha',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirme sua Senha'
        }),
        error_messages={
            'required': '* campo obrigratorio'
        },
        validators=[strong_password]
    )


    class Meta:
        model =  User
        fields = ['first_name',
                  'last_name',
                  'email',
                  'username',
                  'password']

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()

        if exists:
            raise ValidationError(
                'Email já cadastrado', code='invalid',
            )
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confiomation_password = cleaned_data.get('password_confirmation')

        if password != confiomation_password:
            raise ValidationError({
                'password': 'A Senha e a Confirmação precisam ser iguais',
                'password_confirmation': 'A Senha e a Confirmação precisam ser iguais'
            }
            )
        return


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        add_placeholder(self.fields['username'], 'Usuário')
        add_placeholder(self.fields['password'], 'Senha')

    username = forms.CharField(
        label='Usuário'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='Senha'
    )

class CadastrarReceitaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.my_errors = defaultdict(list)



        add_placeholder(self.fields['tittle'], 'Titulo')
        add_placeholder(self.fields['description'], 'Descrição')
        add_placeholder(self.fields['cover'], 'Capa')
        add_placeholder(self.fields['category'], 'Categoria')
        add_placeholder(self.fields['preparation_time'], 'Tempo de Preparo')
        add_placeholder(self.fields['servings_steps'], 'Quantas Porções Rendem')
        add_placeholder(self.fields['preparation_time_unit'], 'Ex.: Minutos, Hora, Horas')
        add_placeholder(self.fields['preparation_steps'], 'Ingrediente e Passo a Passo de Preparo')


    class Meta:
        model = Recipe
        fields = ['tittle','description', 'category', 'preparation_time', 'preparation_time_unit', 'servings_steps','cover', 'preparation_steps' ]

    tittle = forms.CharField(
        required=True,
        label= 'Titulo da Receita',
        error_messages={
            'required': '* campo obrigratorio'
        }
    )

    description = forms.CharField(
        required=True,
        label='Descrição ',
    )

    porcoes_choices = [(porcoes, str(porcoes)) for porcoes in range(1, 21)]

    servings_steps = forms.ChoiceField(
        required=True,
        label='Quantidade de Rendimento',
        choices=porcoes_choices,
    )
    tempo_choices = [(porcoes, str(porcoes)) for porcoes in range(1, 61)]
    preparation_time = forms.ChoiceField(
        label='Tempo de preparo',
        choices=tempo_choices
    )

    preparation_time_unit = forms.CharField(
        required=True,
        label='Unidade de Tempo de Preparo',
        widget = forms.Select(
            choices=(
                ('minutos', 'Minutos'),
                ('horas', 'Horas'),
            )
        )
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=True,
        label='Categoria',
        empty_label='Selecione a categoria',
    )

    preparation_steps = forms.CharField(
        required=True,
        label='Ingredientes e Passo a Passo',
        widget=forms.Textarea()
    )

    def clean(self):
        super_clean = super().clean()

        cleanded_data = self.cleaned_data
        tittle = cleanded_data.get('tittle')
        description = cleanded_data.get('description')


        if len(tittle) < 5:
            self.my_errors['tittle'].append('Deve ao menos 5 catacteres')

        if tittle == description:
            self.my_errors['tittle'].append('Titulo nao deve ser igual a Descrição')
            self.my_errors['description'].append('Descrição nao deve ser igual ao Titulo ')



        if self.my_errors:
            raise ValidationError(self.my_errors)
        return super_clean

authors/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm, CadastrarReceitaForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from utils.pagination import make_pagination
from recipes.models import Recipe
from django.utils.text import slugify
from django.shortcuts import get_object_or_404

import os
# Create your views here.


PER_PAGE = os.environ.get('PER_PAGE', 3)

def register(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(request,'authors/register.html', {
        'form': form,
    })

def register_create(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, 'Você foi cadastrado com sucesso')

        del(request.session['register_form_data'])
        return redirect(reverse('authors:login'))
    return redirect('authors:register')


def login_view(request):
    if request.user.is_authenticated:
        logout(request)

    form = LoginForm()

    return render(request,'authors/login.html', {
        'form': form,
        'form_action': reverse('authors:login_create')
    })

def login_create(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)
    login_url = reverse('authors:login')

    if form.is_valid():
        authenticated_user = authenticate(request,
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            login(request, authenticated_user)
            return redirect('authors:pagina_de_usuario')
        else:
            messages.error(request,'Usuario ou senha incorretos')
    else:
        messages.error(request, 'Usuario ou senha incorretos')

    return redirect(login_url)

@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        messages.error(request, 'Invalid request')
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        messages.error(request, 'Divergent User')
        return redirect(reverse('authors:login'))

    logout(request)
    messages.success(request, 'Logout User')
    return redirect(reverse('authors:login'))

@login_required(login_url='authors:login', redirect_field_name='next')
def pagina_de_usuario(request):
    return render(request, 'authors/pagina_de_usuario.html')


@login_required(login_url='authors:login', redirect_field_name='next')
def cadastrar_receita(request):
    if request.method == "POST":
        form = CadastrarReceitaForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.is_published = False

            if not recipe.id:
                base_slug = slugify(recipe.tittle)
                slug = base_slug
                counter = 1
                while Recipe.objects.filter(slug=slug).exists():
                    slug = f"{base_slug}-{counter}"
                    counter += 1
                recipe.slug = slug

            recipe.save()
            messages.success(request,'recipe cadastrada com sucesso')

            return redirect('authors:pagina_de_usuario')
        else:
            messages.error('Receita nao cadastrada. Verifique os campos e tente novamente')
    else:
        form = CadastrarReceitaForm()

    return render(request, 'authors/cadastrar_receita.html', context={'form':form})


@login_required(login_url='authors:login', redirect_field_name='next')
def receitas_publicadas(request):
    recipes = Recipe.objects.filter(author=request.user, is_published=True)
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'authors/receitas_publicadas.html',
    context = {
        'recipes': page_object,
        'pagination_range': pagination_range,
    })

@login_required(login_url='authors:login', redirect_field_name='next')
def receitas_em_revisao(request):
    recipes = Recipe.objects.filter(author=request.user, is_published=False)
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'authors/receitas_em_revisao.html',
    context = {
        'recipes': page_object,
        'pagination_range': pagination_range,
        'from_painel_de_usuario': True
    })

@login_required(login_url='authors:login')
def apagar_receita(request, id):
    recipe = get_object_or_404(Recipe, id=id, author=request.user)

    if request.method == "POST":
        recipe.delete()
        messages.success(request, "Receita apagada com sucesso!")
        return redirect('authors:pagina_de_usuario')
    else:
        messages.error(request, "Ação inválida.")
        return redirect('authors:pagina_de_usuario')

@login_required(login_url='authors:login')
def editar_receita(request, id):
    recipe = get_object_or_404(Recipe, id=id)

    if request.method == 'POST':
        form = CadastrarReceitaForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            messages.success(request, 'Receita editada com sucesso')
            return redirect('authors:pagina_de_usuario')
        else:
            messages.error(request, 'algo deu errao verifique e tente novamente')
            form = CadastrarReceitaForm(instance=recipe)

    else:
        form = CadastrarReceitaForm(instance=recipe)
    return render(request,'authors/editar_receita.html', {'form':form, 'recipe':recipe})

authors/templates/authors/cadastrar_receita.html
{% extends 'base.html' %}

{% block title %}
Cadastrar Receita
{% endblock %}
{% block body %}
<div class="main-content container">
    <h2 class="center text-user-perfil">Cadastrar Receita</h2>
    <form action="{% url 'authors:cadastrar_receitas' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partials/forms.html' %}
        <div class="form-group form-content-grid center">
            <button type="submit">Cadastrar</button>
        </div>
        <div class="form-group form-content-grid center">
            <a href="{% url 'authors:pagina_de_usuario' %}">
                <button type="button">Voltar</button>
            </a>
        </div>
    </form>
</div>
{% endblock %}

authors/templates/authors/editar_receita.html
{% extends 'base.html' %}

{% block title %}
Editar
{% endblock %}
{% block body %}
<div class="main-content container">
    <h2 class="center text-user-perfil">Editar Receita</h2>
    <form action="{% url 'authors:editar_receita' recipe.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partials/forms.html' %}
        {% if form.errors %}
        <div class="form-content form-content-grid">
            <div class="form-group">
                <div class="message message-error">
                    Não foi possível Cadastrar essa receita. Verifique os campos e tente novamente.
                </div>
            </div>
        </div>
        {% endif %}

        <div class="form-group form-content-grid center">
            <button type="submit">Salvar</button>
        </div>
        <div class="form-group form-content-grid center">
            <a href="{% url 'authors:pagina_de_usuario' %}">
                <button type="button">Voltar</button>
            </a>
        </div>
    </form>
</div>
{% endblock %}

authors/templates/authors/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}
{% block body %}
<div class="main-content container">
    <H1 class="h1-login-cadastro">LOGIN</H1>
    <form action="{% url 'authors:login_create' %}" method="POST">
        {% csrf_token %}
        {% include 'partials/forms.html' %}
        {% if form.errors %}
        <div class="form-content form-content-grid">
            <div class="form-group">
                <div class="message message-error">
                    Não foi possível concluir o Login. Verifique os campos e tente novamente.
                </div>
            </div>
        </div>
        {% endif %}
        <div class="form-group form-content-grid">
            <button type="submit">Login</button>
        </div>
    </form>
</div>
{% endblock %}

authors/templates/authors/pagina_de_usuario.html
{% extends 'base.html' %}

{% block title %}
{{ request.user.username }}
{% endblock %}
{% block body %}
<h2 class="center text-user-perfil">Bem Vindo {{ request.user.username }}! </h2>
{% if messages %}
  <div class="center">
    {% for message in messages %}
      <div class="message {{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}

<div class="form-group form-content-grid center">
    <a href="{% url 'authors:receitas_publicadas' %}">
      <button type="button">Receitas publicadas</button>
    </a>
</div>
<div class="form-group form-content-grid center">
    <a href="{% url 'authors:receitas_em_revisao' %}">
      <button type="button">Receitas em Revisão</button>
    </a>
</div>
<div class="form-group form-content-grid center">
    <a href="{% url 'authors:cadastrar_receitas' %}">
      <button type="button">Cadastrar Receita</button>
    </a>
</div>

<form action="{% url 'authors:logout' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="username" value="{{ request.user.username }}">
    <div class="form-group form-content-grid">
        <button type="submit">Sair</button>
    </div>
</form>

{% endblock %}

authors/templates/authors/receitas_em_revisao.html
{% extends 'base.html' %}

{% block title %}
receitas em revisao {{ request.user.username }}
{% endblock %}
{% block body %}
{% include 'recipes/partials/search.html' %}
<h2 class="center text-user-perfil">Receitas em Revisão de {{ request.user.username }}! </h2>
<div class="main-content-container">
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% if recipe.author == request.user %}
                {% include 'recipes/partials/recipe.html' %}
        {% endif %}
        {% empty %}
            <h1>Nenhuma Receita a ser Revisada</h1>
        {% endfor %}
    </div>
    <div class="form-group form-content-grid center">
        <a href="{% url 'authors:pagina_de_usuario' %}">
          <button type="button">Voltar</button>
        </a>
    </div>
</div>
{% endblock %}

authors/templates/authors/receitas_publicadas.html
{% extends 'base.html' %}

{% block title %}
Receitas Publicadas {{ request.user.username }}
{% endblock %}
{% block body %}
{% include 'recipes/partials/search.html' %}
<h2 class="center text-user-perfil">Receitas publicadas</h2>
<div class="main-content-container">
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% if recipe.author == request.user %}
                {% include 'recipes/partials/recipe.html' %}
            {% endif %}
        {% empty %}
            <h1>Nenhuma Receita Publicada</h1>
        {% endfor %}
    </div>
    <div class="form-group form-content-grid center">
        <a href="{% url 'authors:pagina_de_usuario' %}">
          <button type="button">Voltar</button>
        </a>
    </div>
</div>
{% endblock %}

authors/templates/authors/register.html
{% extends 'base.html' %}

{% block title %}
Cadastro
{% endblock %}
{% block body %}
<div class="main-content container">
    <H1 class="h1-login-cadastro">CADATRO</H1>
    <form action="{% url 'authors:create' %}" method="POST">
        {% csrf_token %}
        {% include 'partials/forms.html' %}
        {% if form.errors %}
            <div class="form-content form-content-grid">
                <div class="form-group">
                    <div class="message message-error">
                        Não foi possível concluir o cadastro. Verifique os campos com erro e tente novamente.
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="form-group form-content-grid">
            <button type="submit">Cadastrar</button>
        </div>
    </form>
</div>

{% endblock %}