authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('cadastro/', views.register, name='register'),
    path('cadastro/create/', views.register_create, name='create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('pagina_de_usuario/', views.pagina_de_usuario, name='pagina_de_usuario'),
    path('pagina_de_usuario/logout', views.logout_view, name='logout'),
    path('receitas_publicadas/', views.receitas_publicadas, name='receitas_publicadas'),
    path('receitas_em_revisao/', views.receitas_em_revisao, name='receitas_em_revisao'),
    path('receitas_em_revisao/editar_receita/<int:id>/', views.editar_receita, name='editar_receita'),
    path('cadastrar_receita/', views.cadastrar_receita, name='cadastrar_receitas'),
    path('apagar_receita/<int:id>/', views.apagar_receita, name='apagar_receita'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
    path('recipes/<int:id>/', views.recipes, name='recipe_detail'),

]

recipesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    tittle = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings_steps = models.IntegerField()
    servings_steps_unit = models.CharField(max_length=65, blank=True, null=True)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.category}: {self.tittle}'

recipes/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.db.models import Q
from .models import Recipe
from django.http import Http404
from utils.pagination import make_pagination
import os

# Create your views here.
PER_PAGE = os.environ.get('PER_PAGE', 3)

def home(request):
    recipes = get_list_or_404(Recipe.objects.order_by('-id'), is_published=True)

    page_object, pagination_range =  make_pagination(request, recipes, PER_PAGE)
    page = request.GET.get('page', 1)
    return render(request, 'recipes/home.html', context={
        'recipes': page_object,
        'pagination_range': pagination_range,
        'page': page,
    })

def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.order_by('-id'), category__id=category_id, is_published=True)
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)



    return render(request, 'recipes/category.html', context={
        'recipes': page_object,
        'pagination_range':pagination_range,
        'title': f'{recipes[0].category.name} | Category',

    })

def recipes(request, id):
    page = request.GET.get('page', 1)

    if request.user.is_authenticated:
        recipe = get_object_or_404(
            Recipe,
            Q(id=id) & (Q(is_published=True) | Q(author=request.user))
        )
    else:
        recipe = get_object_or_404(
            Recipe,
            id=id,
            is_published=True
        )

    return render(request, 'recipes/recipes_description.html', context={
        'recipe': recipe,
        'is_datail_page': True,
        'page': page
    })

def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = (Recipe.objects.filter(
            Q(Q(tittle__icontains = search_term) |
                    Q(description__icontains = search_term)),
            is_published=True,).order_by('-id'))
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/search_view.html', context={
        'title': f'q "{search_term}"',
        'search_term': search_term,
        'recipes': page_object,
        'pagination_range':pagination_range,
        'aditional_url_query': f'&q={search_term}',
    })

recipes/templates/recipes/category.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
    {% include 'recipes/partials/search.html' %}
    <div class="main-content-container">
        <div class="main-content main-content-list container">
            {% for recipe in recipes %}
                {% include 'recipes/partials/recipe.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

recipes/templates/recipes/home.html
{% extends 'base.html' %}

{% block title %}
HomePage
{% endblock %}

{% block body %}
{% include 'recipes/partials/search.html' %}
{% include 'partials/messages.html' %}

<div class="main-content-container">
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html' %}
        {% empty %}
            <h1>Nenhuma Receita Publicada</h1>
        {% endfor %}
    </div>
</div>

{% endblock %}

recipes/templates/recipes/recipe_description.html
{% extends 'base.html' %}

{% block title %}
Receita Detalhada
{% endblock %}

{% block body %}
    <div class="main-content-container">
        <div class="main-content main-content-detail container">
            {% include 'recipes/partials/recipe.html' %}
        </div>
    </div>
{% endblock %}

recipes/templates/recipes/recipes_description.html
{% extends 'base.html' %}

{% block title %}
{{ recipe.tittle }}
{% endblock %}

{% block body %}
    {% include 'recipes/partials/search.html' %}
    <div class="main-content-container">
        <div class="main-content main-content-detail container">
            {% include 'recipes/partials/recipe.html' %}
        </div>
    </div>
    <div class="form-group form-content-grid center">
        {% if request.resolver_match.url_name == "receitas_em_revisao" %}
            <a href="{% url 'authors:receitas_em_revisao' %}">
              <button type="button">Voltar</button>
            </a>
        {% endif %}

        <a href="{% url 'recipes:home' %}?page={{ page }}">
          <button type="button">Voltar</button>
        </a>
    </div>
{% endblock %}

recipes/templates/recipes/search_view.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}
{% block body %}
    {% include 'recipes/partials/search.html' %}
    <div class="main-content-container">
        <div class="main-content main-content-list container">
            {% for recipe in recipes %}
                {% include 'recipes/partials/recipe.html' %}
            {% empty %}
                <h1>Nenhuma Receita Publicada</h1>
            {% endfor %}
        </div>
    </div>
{% endblock %}