authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('cadastro/', views.register, name='register'),
    path('cadastro/create/', views.register_create, name='create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('pagina_de_usuario/', views.pagina_de_usuario, name='pagina_de_usuario'),
    path('pagina_de_usuario/logout', views.logout_view, name='logout'),
    path('receitas_publicadas/', views.receitas_publicadas, name='receitas_publicadas'),
    path('receitas_em_revisao/', views.receitas_em_revisao, name='receitas_em_revisao'),
    path('receitas_em_revisao/editar_receita/<int:id>/', views.editar_receita, name='editar_receita'),
    path('cadastrar_receita/', views.cadastrar_receita, name='cadastrar_receitas'),
    path('apagar_receita/<int:id>/', views.apagar_receita, name='apagar_receita'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
    path('recipes/<int:id>/', views.recipes, name='recipe_detail'),

]

recipesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    tittle = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings_steps = models.IntegerField()
    servings_steps_unit = models.CharField(max_length=65, blank=True, null=True)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.category}: {self.tittle}'

recipes/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.db.models import Q
from .models import Recipe
from django.http import Http404
from utils.pagination import make_pagination
import os

# Create your views here.
PER_PAGE = os.environ.get('PER_PAGE', 3)

def home(request):
    recipes = get_list_or_404(Recipe.objects.order_by('-id'), is_published=True)

    page_object, pagination_range =  make_pagination(request, recipes, PER_PAGE)
    page = request.GET.get('page', 1)
    return render(request, 'recipes/home.html', context={
        'recipes': page_object,
        'pagination_range': pagination_range,
        'page': page,
    })

def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.order_by('-id'), category__id=category_id, is_published=True)
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)



    return render(request, 'recipes/category.html', context={
        'recipes': page_object,
        'pagination_range':pagination_range,
        'title': f'{recipes[0].category.name} | Category',

    })

def recipes(request, id):
    page = request.GET.get('page', 1)

    if request.user.is_authenticated:
        recipe = get_object_or_404(
            Recipe,
            Q(id=id) & (Q(is_published=True) | Q(author=request.user))
        )
    else:
        recipe = get_object_or_404(
            Recipe,
            id=id,
            is_published=True
        )

    return render(request, 'recipes/recipes_description.html', context={
        'recipe': recipe,
        'is_datail_page': True,
        'page': page
    })

def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = (Recipe.objects.filter(
            Q(Q(tittle__icontains = search_term) |
                    Q(description__icontains = search_term)),
            is_published=True,).order_by('-id'))
    page_object, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/search_view.html', context={
        'title': f'q "{search_term}"',
        'search_term': search_term,
        'recipes': page_object,
        'pagination_range':pagination_range,
        'aditional_url_query': f'&q={search_term}',
    })

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe_detail' recipe.id %}">
                 <img src="{{ recipe.cover.url }}" alt="temporario">
            </a>
        </div>
    {% endif %}

    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe_detail' recipe.id %}">
                {{ recipe.tittle }}
            </a>
        </h2>
    </div>
     <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href=" {% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

     <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings_steps }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>
    {% if user.is_authenticated and from_painel_de_usuario %}
        <div class="recipe-footer">
            <a href="{% url 'authors:editar_receita' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                <i class="fas fa-edit"></i> Editar
            </a>
            <form class="form-delete" id="delete-form-{{ recipe.id }}" action="{% url 'authors:apagar_receita' recipe.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="recipe-read-more button button-dark button-full-width">
                    <i class="fas fa-trash"></i> Apagar
                </button>
</form>
        </div>
    {% endif %}
    {% if is_datail_page is not True and not from_painel_de_usuario %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe_detail' recipe.id %}?page={{ recipes.number }}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
    {% if is_datail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
  <div class="container">
    <form action="{% url 'recipes:search' %}" class="search-form" >
      <input type="search" class="search-input" name="q" value="{{ search_term }}" required placeholder="Qual receita esta procurando">
      <button type="submit" class="search-button"><i class="fas fa-search"></i> </button>
    </form>
  </div>
</div>